### ISSUE TITLE
Camera not working on some devices

### ISSUE THREAD

**Issue by danielpinto8zz6** [TheStrix/android_kernel_xiaomi_msm8956#1]
hi, I reported that camera not works on some devices,
I replaced with marshmallow blobs and still not working, on santosh build (with prebuilt kernel) camera works, so I think this is some kernel problem or missing part.
Thank you

**Comment by balika011** [comment]
I think it's fixed. :+1:

**Comment by danielpinto8zz6** [comment]
yes
